### ISSUE TITLE
app not compatible with nextcloud 16.0.1

### ISSUE THREAD

**Issue by neddstark** [nextcloud/privacy#118]
app not compatible with nextcloud 16.0.1 ?

**Comment by georgehrke** [comment]
It is supposed to. Please fill out the issue template if there is a bug.

**Comment by neddstark** [comment]
I am on NC 16.0.0 and on the upgrades page, it says 16.0.1 is available, but this app is missing updates.

When I click on it, it takes me to a page not found:
https://apps.nextcloud.com/apps/privacy <https://apps.nextcloud.com/apps/privacy>

Attaching a screenshot.

**Comment by georgehrke** [comment]
>  it says 16.0.1 is available, but this app is missing updates.

What exactly do you mean by this app is missing updates?
Is that referring to an error message inside Nextcloud? 

Can you please post a screenshot in that case.

> When I click on it, it takes me to a page not found:
https://apps.nextcloud.com/apps/privacy <https://apps.nextcloud.com/apps/privacy>

That is no wonder, because the app is not distributed via the App Store but shipped as part of the release.

**Comment by neddstark** [comment]
Yes, the notifcation is inside nextcloud updates page.

So in this case I can update NC without any issues for Privacy app?

Sorry in this case, I am not very familiar with the NC apps ecosystem.

**Comment by neddstark** [comment]
See attached screenshot on my previous comments.

**Comment by georgehrke** [comment]
> Sorry in this case, I am not very familiar with the NC apps ecosystem.

Don't worry, absolutely not your fault. This error message should obviously not be there. That seems to be a bug in the Nextcloud server.

**Comment by georgehrke** [comment]
Pull-request in server: https://github.com/nextcloud/server/pull/15582

**Comment by georgehrke** [comment]
I will close this ticket, because this is no bug in the privacy app but a bug in the Nextcloud server.
The pull-request mentioned above will fix the issue and should (hopefully) be included in Nextcloud 16.0.2.

In the meantime its save to simply ignore that warning and update to 16.0.1. The privacy and the recommendations app will keep working.

**Comment by neddstark** [comment]
Thank you much!
