### ISSUE TITLE
Translations are not synced 

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/privacy#166]
Translations are not synced as the huge number of country names are untranslated e.g. in Swedish. This means even if the other strings are translated the translations will not be pushed to the repo. 

@MorrisJobke Is there any workaround we could apply here? Where is the limit configured?

**Comment by MorrisJobke** [comment]
The threshold is currently configured as 25% in https://github.com/nextcloud/docker-ci/blob/master/translations/handleAppTranslations.sh#L66, but we maybe can go lower. What percentage would be needed here? I guess 1% is fine as well, because for apps it doesn't really matter. The core and lib one are used to identify which translations are available.

**Comment by MorrisJobke** [comment]
Changed it to 5%. https://github.com/nextcloud/docker-ci/commit/5c2b632ec4affafa0734691123dcad00f641e95f
