### ISSUE TITLE
Settings > Privacy > Encryption not saved on fresh NC 19 install

### ISSUE THREAD

**Issue by mjog** [nextcloud/privacy#427]
Changing the Settings > Privacy > Encryption setting as admin user is not saved on fresh NC 19 install.

### Steps to reproduce
1. Log in as admin user
2. Go to Settings > Privacy > Encryption, click edit button
3. Tick the "This server is using full-disk encryption" checkbox

### Expected behaviour

On reload, "This server is protected with full-disk-encryption" is displayed.

### Actual behaviour

On reload, "You files are not protected by encryption" is displayed

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2.4.38

**Database:** Maria 10.3.22

**PHP version:** 7.3

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Downloaded tar.gz

**Comment by ph00lt0** [comment]
Same issue is present in the snap image.

**Comment by georgehrke** [comment]
Please fill the entire issue template and provide logs as well ...

**Comment by ph00lt0** [comment]
It's the LTS snap, running on Ubuntu 20. All other versions are controlled by the snap, so I see no point filling the full template.

**Comment by georgehrke** [comment]
Unless you fill out the issue template completely including all logs, we can't go ahead and help you. If no one is able to provide logs, this issue will automatically be closed in 21 days.

**Comment by ph00lt0** [comment]
@georgehrke sounds like a policy closing issues of bugs that are in current LTS lol. There are no error logs on this.

**Comment by georgehrke** [comment]
@ph00lt0 Did you check the browser log?

**Comment by ph00lt0** [comment]
If you mean console log, nothing to see there other then deprecated jquery version warning.

**Comment by georgehrke** [comment]
Can you still fill the issue template please? I need config.php, enabled apps, etc.

**Comment by ph00lt0** [comment]
No enabled apps other then default, config is just directly as in [snap](https://vuldb.com/?id.157485) I just installed a clean installation of nextcloud snap.

**Comment by jonknud** [comment]
Hello Together,
I have the same problem with a fresh install of nextcloud via docker (nextcloud:19-fpm). How can I help to solve this? Where can I find the issue template? I coundn't find it though google.

**Comment by aszlig** [comment]
The regression is in c0615e3a55885e341bb82e2f8fdb3b2f8e6f49c9, where on the frontend the values for `fullDiskEncryptionEnabled` and `serverSideEncryptionEnabled` **were** matched against [the string `'1'`](https://github.com/nextcloud/privacy/commit/c0615e3a55885e341bb82e2f8fdb3b2f8e6f49c9#diff-1c90ff38a08209f9ebd4d05d1e43358eL57-L58) and are **now** matched [against the integer `1`](https://github.com/nextcloud/privacy/commit/c0615e3a55885e341bb82e2f8fdb3b2f8e6f49c9#diff-66e2182ed8cd210f3b382b25cb8e328fR97-R98).

However, [the backend](https://github.com/nextcloud/privacy/commit/c0615e3a55885e341bb82e2f8fdb3b2f8e6f49c9#diff-1d757efc12b8f21a5055658738fd6c5dR75-R76) was (and [is](https://github.com/nextcloud/privacy/blob/ecfd201e9c1cd7332d4e2bb08411612cc3736cf2/lib/Settings/WhoHasAccessSettings.php#L75-L76)) still returning strings.

So the fix for this is to either change the comparison on the frontend to use strings or the backend to emit integers instead.
